learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
from . import views
from django.urls import path

app_name = 'learning_logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics', views.topics, name='topics'),
    path('topics/<int:topic_id>', views.topic, name='topic'),
    path('new_topic', views.new_topic, name='new_topic'),
    path('delete_topic/<int:topic_id>', views.delete_topic, name='delete_topic'),
    path('new_entry/<int:topic_id>', views.new_entry, name="new_entry"),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    path('delete_entry/<int:entry_id>', views.delete_entry, name='delete_entry'),
]

users/urls.py
# users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models


class Topic(models.Model):
    """ A topic the user is learning aabout """
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """ return a string representation of the model """
        return self.text


class Entry(models.Model):
    """ something specific learned about topic """
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': 'write here...'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80, 'placeholder': 'add entry'})}

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text="optional")
    last_name = forms.CharField(max_length=30, required=False, help_text="optional")
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

learning_logs/views.py
from django.shortcuts import render, redirect
from .forms import TopicForm, EntryForm
from .models import Topic, Entry
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """ show all topics """
    topics = Topic.objects.all()
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """show a topic and all its entries"""
    topic = Topic.objects.get(id=topic_id)
    entries = Entry.objects.filter(topic_id=topic_id)
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """add a new topic"""
    if request.method != "POST":
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'form': form, 'topic': topic}

    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=entry.topic.id)
    context = {'entry': entry, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context),

@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    entry.delete()

    return redirect('learning_logs:topic', topic_id=topic.id)

@login_required
def delete_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    topic.delete()

    return redirect('learning_logs:topics')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from .forms import RegisterForm


# Create your views here.
def register(request):
    if request.method != 'POST':
        form = RegisterForm()
    else:
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
        
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        a {
            text-decoration: none;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning log</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Çıkış Yap</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Giriş Yap</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Kayıt Ol</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:topic' entry.topic.id %}">{{ entry.topic}}</a>
    </p>
    <p>edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button name="submit">Save</button>
        <button name="reset" type="reset">Reset</button>
    </form>
{% endblock %}

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning Log</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    {% block content %}
    <h1 class="text-center">Learning log</h1>
    <div class="container py-4">
        <div class="p-5 mb-4 bg-body-tertiary rounded-3">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold">Track Your Learning Progress</h1>
                <p class="col-md-8 fs-4">Create your own personalized learning log. Keep track of the topics you're learning about.
                Whenever discover something new, log it to summarize what you've learned and track your progress.</p>
                    <a href="{% url 'users:register' %}" class="btn btn-primary btn-lg">Get Started</a>
            </div>
        </div>
    </div>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
    </p>
    <p>add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add entry</button>
        <button type="reset" name="reset">reset</button>
    </form>
{% endblock %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>add a new topic:</p>
    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" name="submit">add topic</button>
        <button name="reset" type="reset">reset</button>
    </form>
{% endblock %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <h3 class="text-center">{{ topic }}</h3>
    <a href="{% url 'learning_logs:new_entry' topic.id %}" class="btn btn-outline-primary my-5">add new entry</a>
    <h5>Entries</h5>
    <ul>
        {% for entry in entries %}
            <div class="card">
                <div class="card-header">
                    {{entry.date_added|date:'M d, Y H:i'}}
                </div>
                <div class="card-body">
                    {{entry.text}}
                </div>
                <div class="card-footer">
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}" class="btn btn-outline-success">edit entry</a>
                    <a href="{% url 'learning_logs:delete_entry' entry.id %}" class="btn btn-outline-danger">delete entry</a>
                </div>
            </div>
        {% empty %}
            <p>bir entry yok</p>
        {% endfor %}
    </ul>
{% endblock %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <h2 class="text-center">Topics</h2>
    <a href="{% url 'learning_logs:new_topic' %}" class="btn btn-outline-success my-3 ms-4" type="button">add a new topic</a>
    <ol>
        
            <div class="d-flex flex-row mb-3">
            {% for topic in topics %}
                <div class="card mx-3" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h5>
                        <p class="card-text">{{ topic.date_added }}</p>
                        <a href="{% url 'learning_logs:delete_topic' topic.id %}" class="text-danger">Delete Topic</a>
                    </div>
                </div>
            {% endfor %}
            </div>
    </ol>
{% endblock content %}